import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';

interface Feature {
  route: string;
  emoji: string;
  title: string;
  subtitle: string;
  accent: string;
}

const FEATURES: Feature[] = [
  {
    route: '/flights/search',
    emoji: '🔎',
    title: 'Search Flights',
    subtitle: 'Anywhere to anywhere, single or multiple travelers',
    accent: '#00D4FF',
  },
  {
    route: '/flights/explore',
    emoji: '🗺️',
    title: 'Cheapest Anywhere',
    subtitle: 'Where can I go from home on the cheap?',
    accent: '#00FF88',
  },
  {
    route: '/flights/builder',
    emoji: '🧩',
    title: 'Connection Builder',
    subtitle: 'Stitch multi-city hops to cut the fare',
    accent: '#0096FF',
  },
  {
    route: '/flights/southwest',
    emoji: '🎫',
    title: 'Southwest Optimizer',
    subtitle: 'Short jumps for tier & Companion Pass',
    accent: '#FFB800',
  },
  {
    route: '/flights/alerts',
    emoji: '🔔',
    title: 'Price Alerts',
    subtitle: 'Get pinged when fares drop below your price',
    accent: '#FF6B9D',
  },
];

export default function FlightsHome() {
  const router = useRouter();
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.hero}>Find your next flight</Text>
      <Text style={styles.heroSub}>
        Live-style fares across every airline, cheapest-anywhere discovery, and real-time
        price alerts.
      </Text>

      {FEATURES.map((f) => (
        <Pressable
          key={f.route}
          style={styles.card}
          onPress={() => router.push(f.route as never)}
        >
          <View style={[styles.iconWrap, { backgroundColor: `${f.accent}22` }]}>
            <Text style={styles.icon}>{f.emoji}</Text>
          </View>
          <View style={styles.cardBody}>
            <Text style={styles.cardTitle}>{f.title}</Text>
            <Text style={styles.cardSub}>{f.subtitle}</Text>
          </View>
          <Text style={[styles.arrow, { color: f.accent }]}>›</Text>
        </Pressable>
      ))}

      <Text style={styles.footnote}>
        Demo prices are generated by a deterministic mock provider. Swap in a real GDS / OTA
        API by implementing the FlightProvider interface.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0A0A0F' },
  content: { padding: 16, paddingBottom: 40 },
  hero: { color: '#FFFFFF', fontSize: 26, fontWeight: '800', marginTop: 4 },
  heroSub: { color: '#8888AA', fontSize: 14, lineHeight: 20, marginTop: 6, marginBottom: 20 },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#12121A',
    borderWidth: 1,
    borderColor: '#1E1E2E',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  iconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: { fontSize: 24 },
  cardBody: { flex: 1, marginLeft: 14 },
  cardTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  cardSub: { color: '#8888AA', fontSize: 13, marginTop: 3, lineHeight: 18 },
  arrow: { fontSize: 28, fontWeight: '300', marginLeft: 8 },
  footnote: {
    color: '#5A5A7A',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
    textAlign: 'center',
  },
});
